### ISSUE TITLE
Maintainer Wanted

### ISSUE THREAD

**Issue by benwilson512** [ex-aws/ex_aws_kms#1]
Hey @hirocaster, per https://elixirforum.com/t/proposal-exaws-2-0/9269 the ExAws project is splitting out each service into its own project.

You are the original contributor the KMS service to ExAws. If you wish to be its maintainer, please let me know and I will give you commit access to this repository. If you do not want this, let me know and I will look for someone else.

Thank you!

**Comment by hirocaster** [comment]
I think that your proposal is realistic and a good plan. 👍 
Please be sure to maintain your project.

I develop and use DynamoDB service ([hirocaster/surge](https://github.com/hirocaster/surge)) at my job. so, I understand `ex_aws_dynamo` at develop.
I can maintenance of `ex_aws_dynamo` is also possible.

Thank you in advance.

**Comment by benwilson512** [comment]
Thank you! I have added you as a maintainer to this repository.

**Comment by hirocaster** [comment]
I accepted your invitation, but, I'm not `ex-aws` organization member.
so, it was created the [forked repository](https://github.com/ex-aws/ex_aws_kms) after accepted.

Is this setting correct?

**Comment by bmuller** [comment]
@hirocaster are you still interested in maintaining?

@davidrichey, @hidnasio, and @artkay also seemed interested in getting an updated release - any of you interested in maintaining?

If no one else wants to take over, I'm willing to step in for now.  I currently need this lib for code I've got in production, so I've got a stake in seeing it get ongoing ❤️ .

**Comment by davidrichey** [comment]
I won't be able to, @bmuller. I am now only using this in side projects. Happy to help when time permits

**Comment by hidnasio** [comment]
I don't have the time currently to help maintaining this library @bmuller, sorry.

**Comment by artkay** [comment]
Hey @benwilson512, I use this in production for a key piece of infrastructure, I am willing to take on responsibility since it looks like no one else is able to.

**Comment by benwilson512** [comment]
Hi @artkay, please send an email to my github username @gmail.com with your hex.pm user name. I've added you as a maintainer to this github repo, please confirm that you can make branches and commits.
