### ISSUE TITLE
ex_aws_kms doesn't work with ex_aws version 2.1.0

### ISSUE THREAD

**Issue by hidnasio** [ex-aws/ex_aws_kms#3]
Hello, thanks for this library.

I'm trying to update ex_aws to version 2.1.0 but ex_aws_kms requires ex_aws v2.0

config in mix.exs

https://github.com/ex-aws/ex_aws_kms/blob/825774577642ee667d74eb28d3544a67a47d7d85/mix.exs#L37

### Environment

* Elixir & Erlang versions (elixir --version):

Elixir 1.7.4 (compiled with Erlang/OTP 21)

* ExAws version `mix deps |grep ex_aws`

ex_aws (Hex package) (mix)
  locked at 2.0.2 (ex_aws) 8df2f96f

* HTTP client version. IE for hackney do `mix deps | grep hackney`

hackney 1.14.3 (Hex package) (rebar3)
  locked at 1.14.3 (hackney) b5f6f5dc

### Current behavior

Doesn't compile with ex_aws v2.1.0

### Expected behavior

Compiles with ex_aws v2.1.0

**Comment by hidnasio** [comment]
Thanks for the quick response.

This is the error I'm getting

```

**Comment by hidnasio** [comment]
Confirmed, the released version in hex.pm requires ex_aws "~> 2.0.0". It works if I use master. Is it possible to release a new version?

**Comment by bmuller** [comment]
+1 on this.  Would be great to be able to use `~> 2.0` for both ex_aws_kms and other libs like ex_aws_s3.

**Comment by davidrichey** [comment]
+1 ☝️
