### ISSUE TITLE
Release version 2.1.0 for hex.pm

### ISSUE THREAD

**Issue by hirocaster** [ex-aws/ex_aws_kms#6]
I think you should publish version 2.1.0 for  [hex.pm](https://hex.pm/packages/ex_aws_kms) 

ref #5 

But, I don't have permission for hex.pm.

If you don't mind, can you release it? @benwilson512 

memo: Don't forget to change README.md
```
def deps do
  [
    {:ex_aws, "~> 2.1"},
    {:ex_aws_kms, "~> 2.1"},
    {:poison, "~> 3.0"},
    {:hackney, "~> 1.9"},
  ]
end
```

**Comment by benwilson512** [comment]
Please send me your hex.pm username to [my github username] @gmail.com, and I'll add you to the project so you can do releases.

**Comment by hirocaster** [comment]
This is mine https://hex.pm/users/hirocaster
and I will send mail.

**Comment by hirocaster** [comment]
Send done.

**Comment by artkay** [comment]
Just published the new version. Thanks, @hirocaster !
